#!/bin/bash

# gnu-bash fix in macos, please install gnu-getopt first
if [[ $(uname) == "Darwin" ]]; then
    if [[ ! -f "/opt/homebrew/opt/gnu-getopt/bin/getopt" ]]; then
    echo "Please install gnu-getopt first"
    echo "\$ brew install gnu-getopt"
    exit 1
    fi
    export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"
fi
#  _       _ _   
# (_)_ __ (_) |_ 
# | | '_ \| | __|
# | | | | | | |_ 
# |_|_| |_|_|\__|
# ps: all fontart generated by figlet
# import all functions and init the env for ubuntu

export Working_DIR=$(pwd)
ORIGINAL_ARGS="$@"
APP=''
ACTION=''
BASE_LOADED=''
OTHER_ARGS=''
function action_loader(){

    export scripts_DIR="$Working_DIR/lib/$1"
    if [ -d "$scripts_DIR" ]; then
    # excute all scripts in the ./lib dir
        info_echo "loading action $1":
        for script in $scripts_DIR/*.sh; do
            if [ -f "$script" ]; then
                source "$script"
                info_echo "    $script loaded"
            fi
        done
    else
        info_echo "the action $1 none exists!"
        exit 1
    fi
}
info_echo(){
  echo "$@"
}
export -f action_loader
action_loader base
main "${ORIGINAL_ARGS[@]}"

action_loader $APP
export base_CMD="$0 $APP "
info_echo "Loading finished"
echo

verb_echo "other args are \"$OTHER_ARGS\""
verb_echo "passed to action: \"$ACTION\""
main $ACTION $OTHER_ARGS
