START_MARKER="#>>>>>>> GENERATED BY BASH FRAMEWORKER >>>>>>>"
END_MARKER="#<<<<<<< GENERATED BY BASH FRAMEWORKER <<<<<<<"

# Function to detect if the section exists
# usage detect_section <file>
detect_section() {
  if grep -q "$START_MARKER" "$1" && grep -q "$END_MARKER" "$1"; then
    verb_echo "Section detected in $1."
    return 0
  else
    verb_echo "Section not found in $1."
    return 1
  fi
}

# Function to write or replace the section
# usage: $0 <content> <file>
write_section() {
  local content="$1"
  local target_file="$2"
  local replacement="$START_MARKER\n$content\n$END_MARKER"
  if detect_section "$2"; then
    # Replace the content between the markers
  sed -i.bak "s|$START_MARKER.*$END_MARKER|$START_MARKER\n$content\n$END_MARKER|" "$target_file"
  verb_echo "content updated in $target_file."
  else
    # Append the new section at the end of the file
    echo -e "\n$replacement" >> "$target_file"
    verb_echo "Section added to $target_file."
  fi
}

# Function to read the content between the markers, seldom used
# usage: $0 <file>
read_section() {
  local target_file="$1"
  if detect_section; then
    return $(awk "/$START_MARKER/{flag=1; next} /$END_MARKER/{flag=0} flag" "$target_file")
  fi
}

# Function to remove created section
# usage: $0 <file>
remove_section() {
  local target_file="$1"
  if detect_section "$target_file"; then
    # Remove the section
    sed -i.bak "/$START_MARKER/,/$END_MARKER/d" "$target_file"
    verb_echo "Section removed from $target_file."
  else
    verb_echo "No section found in $target_file."
  fi
}